sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service --key-file service-account.json
    - gcloud config set project seventh-atom-265314
    - gcloud config set compute/zone europe-west1-d
    - gcloud container clusters get-credentials standard-cluster-1
    - echo "$DOCKER_PASSWORD"  docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t jwsenselabs/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true jwsenselabs/react-test npm run test

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master