apiVersion: v1
kind: Service
metadata:
    name: client-cluster-ip-service
spec:
    type: ClusterIP
    selector: 
        component: web
    ports:
        # so können die anderen services mich erreichen
        - port: 3000
        # der traffic wird auf den target port der zugehörigen componente web gemappt
          targetPort: 3000