apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template: 
        metadata:
            labels: 
                component: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: database-persistent-volume-claim
            containers:
                - name: postgres
                  image: postgres
                  ports:
                    - containerPort: 5432
                  volumeMounts:
                    - name: postgres-storage
                    # das verzeichnis, wo postgres seine daten auf der festplatte speichert
                      mountPath: /var/lib/postgresql/data
                      # mountet das verzeichnis im ordner postgres (ist postgres-spezifisches verhalten, sieht man sonst nicht so oft)
                      subPath: postgres
                  env:
                    - name: PGPASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: pgpassword
                            key: PGPASSWORD


